### ISSUE TITLE
Resizing window results in title bar misplacement

### ISSUE THREAD

**Issue by wagoodman** [wagoodman/docker-image-explorer#12]
This is apparent by observing the first line in the terminal after resizing

**Comment by wagoodman** [comment]
Fixed by c961041ec336fec1ff1f666d2d5d0141b684251a

**Comment by 1138-4EB** [comment]
I think I'm hitting this same issue, but it affects not only the title bar:

![dive](https://user-images.githubusercontent.com/6628437/63480357-e6068600-c491-11e9-955f-7c843967bd12.gif)
