### ISSUE TITLE
Whole tree expands when layer selection is changed

### ISSUE THREAD

**Issue by willmurphyscode** [wagoodman/docker-image-explorer#4]
To repro

1. View a tree, go to the main view.
2. CTRL + space over to the left side view
3. Move press down arrow

Expected behavior:

Collapsed nodes that exist in both views should stay collapsed

Actual behavior:

Entire tree re-expands.

**Comment by wagoodman** [comment]
Yeah, this is because we rebuild the entire tree from the bottom layer, ignoring any metadata on the existing tree (such as `collapsed`).

**Comment by wagoodman** [comment]
(only fixed the collapsed state, no other metadata yet needs this preservation)
